name: cmip7-guidance
channels:
  - conda-forge
  - nodefaults 
dependencies:
  - mike=2.0.0
  - mkdocs=1.5.3
  - mkdocs-autorefs=1.0.1
  - mkdocs-gen-files=0.4.0
  - mkdocs-literate-nav=0.4.1
  - mkdocs-material=8.5.11
  - mkdocs-material-extensions=1.3.1
  - mkdocstrings=0.24.1
  - mkdocstrings-python=1.9.0
  - pip=21.2.4
  - pip:
    - mkdocs-section-index==0.3.8
